name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # Adjust the PHP version as per your project
          extensions: mbstring, bcmath, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

      - name: Set up application environment
        run: composer run post-root-package-install

      - name: Generate application key
        run: php artisan key:generate --ansi

      - name: Sail installation
        run: php artisan sail:install --with=mysql,redis,meilisearch,mailpit,selenium

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -u laravel -ppassword --silent; then
              break
            fi
            sleep 5
          done

      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: sail
          DB_PASSWORD: password
        run: php artisan migrate --force

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: sail
          DB_PASSWORD: password
        run: php artisan test

      - name: Run Laravel pint
        run: ./vendor/bin/pint --diff=main
